# Generated by Django 2.0.3 on 2018-05-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.IntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('website_slug', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('rank', models.IntegerField(blank=True, default=None, null=True)),
                ('circulating_supply', models.FloatField(blank=True, default=None, null=True)),
                ('total_supply', models.FloatField(blank=True, default=None, null=True)),
                ('max_supply', models.FloatField(blank=True, default=None, null=True)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('volume_24h', models.FloatField(blank=True, default=None, null=True)),
                ('market_cap', models.FloatField(blank=True, default=None, null=True)),
                ('percent_change_1h', models.FloatField(blank=True, default=None, null=True)),
                ('percent_change_24h', models.FloatField(blank=True, default=None, null=True)),
                ('percent_change_7d', models.FloatField(blank=True, default=None, null=True)),
                ('last_updated', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('website_slug', models.CharField(max_length=100)),
            ],
        ),
    ]
